---
openapi: 3.0.0
info:
  title: Genrel Api
  description: Api that did not need Authentication
  version: 1.0.0
servers:
- url: http://localhost:3000/
paths:
  /user/signup:
    post:
      tags:
      - User
      summary: Creates a user.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                genreList:
                  type: array
                  items:
                    type: string
        required: true
      responses:
        "201":
          description: User Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
  /user/login:
    post:
      tags:
      - User
      summary: Login a user.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
        required: true
      responses:
        "200":
          description: Auth Sucessful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
  /book:
    get:
      tags:
      - Book
      summary: Returns a list of Books.
      responses:
        "200":
          description: A Array of Books
          content:
            application/json:
              schema:
                type: object
                properties:
                  Books:
                    type: array
                    items:
                      type: object
  /book/{isbn}:
    get:
      tags:
      - Book
      summary: Returns a list of Books.
      parameters:
      - name: isbn
        in: path
        description: Book ISBN
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: A Array of Books
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  ISBN:
                    type: integer
                  Title:
                    type: string
                  Author:
                    type: string
                  Description:
                    type: string
                  Publication-year:
                    type: string
                  image-url:
                    type: string
                  image-url-s:
                    type: string
  /genre:
    get:
      tags:
      - Genre
      summary: Returns a list of Genres.
      responses:
        "200":
          description: A Array of Genres
          content:
            application/json:
              schema:
                type: object
                properties:
                  Genres:
                    type: array
                    items:
                      type: object
